version: '3.8'
services:
  auth_service:
    build:
      context: ./services/auth_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://auth_user:admin@auth_db/auth_db
    depends_on:
      auth_db:
        condition: service_healthy
    restart: always

  auth_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  news_service:
    build:
      context: ./services/news_service
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql://news_user:admin@news_db/news_db
    depends_on:
      news_db:
        condition: service_healthy
    restart: always

  news_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=news_user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=news_db
    ports:
      - "5437:5432"
    volumes:
      - news_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news_user -d news_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://157.245.68.235:8001
      - REACT_APP_NEWS_SERVICE_URL=http://157.245.68.235:8005
    depends_on:
      - auth_service
      - news_service
    restart: always

volumes:
  auth_postgres_data:
  news_postgres_data:
