name: Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug and Deploy
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
            cd /var/www/kabanforum/kaban
            git reset --hard
            git pull
            # Force recreation of containers
            docker-compose down
            docker-compose rm -f
            docker-compose pull
            docker system prune -f
            # docker-compose up -d --build --force-recreate
            sudo cp ./nginx/nginx.conf /etc/nginx/sites-available/kabanforum
            sudo ln -s /etc/nginx/sites-available/kabanforum /etc/nginx/sites-enabled/
            sudo nginx -t && sudo systemctl reload nginx
          EOF